name: "Haneva Home"
version: "0.9.7"
slug: "haneva_home"
description: "Domovský rozcestník pro rozpočet, společný kalendář a nákupy."
init: false
startup: application
boot: auto
stage: experimental
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
  - i386
ports:
  8100/tcp: 8100
ports_description:
  8100/tcp: "Webové rozhraní Haneva Home"
webui: "http://[HOST]:[PORT:8100]/"
map:
  - type: share
    read_only: false
url: "https://github.com/hanych420/rozpocet-domacnosti-ha"
