from __future__ import annotations

from datetime import datetime, timezone
from urllib.parse import urlparse
import hashlib
import json
import os
import re

import requests

import shopping_official_base as core

VERSION = "0.10.0"
HA_STATES_URL = "http://supervisor/core/api/states"
PARSE_BASE = "https://api.parse.bot/scraper/1959d942-293a-4889-8d0c-9ecdcfdfa36e"
SOURCE_PREFIX = "integration-v100:"


def _log(message):
    print(f"[Haneva][Akce {VERSION}] {message}", flush=True)


def _now_iso():
    return datetime.now(timezone.utc).isoformat()


def _options():
    try:
        with open("/data/options.json", "r", encoding="utf-8") as fh:
            data = json.load(fh)
            return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _walk(value):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from _walk(child)
    elif isinstance(value, list):
        for child in value:
            yield from _walk(child)


def _meta_get(key):
    try:
        with core.db() as conn:
            row = conn.execute("SELECT value FROM shopping_sync_meta WHERE key=?", (key,)).fetchone()
        return row["value"] if row else None
    except Exception:
        return None


def _meta_set(key, value):
    with core.db() as conn:
        conn.execute(
            """
            INSERT INTO shopping_sync_meta(key, value, updated_at)
            VALUES(?,?,?)
            ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at
            """,
            (key, str(value), _now_iso()),
        )
        conn.commit()


def _count_external(store):
    with core.db() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS n FROM official_deals WHERE store=? AND source_kind='official' AND source_fingerprint LIKE ?",
            (store, SOURCE_PREFIX + "%"),
        ).fetchone()
    return int(row["n"] if row else 0)


def _clear_legacy_rows(store):
    """Remove rows generated by our retired HTML/PDF parsers, once."""
    key = f"v100_legacy_cleared_{store}"
    if _meta_get(key) == "1":
        return
    with core.db() as conn:
        conn.execute(
            "DELETE FROM official_deals WHERE store=? AND source_kind='official' AND (source_fingerprint IS NULL OR source_fingerprint NOT LIKE ?)",
            (store, SOURCE_PREFIX + "%"),
        )
        conn.commit()
    _meta_set(key, "1")


def _replace_store(store, deals, fingerprint):
    cleaned = []
    seen = set()
    for deal in deals:
        name = core._clean(deal.get("name"))
        current = core._float_price(deal.get("price_value") or deal.get("price_text"))
        if not name or current is None or current <= 0:
            continue
        valid_from = core._iso_date(deal.get("valid_from"))
        valid_to = core._iso_date(deal.get("valid_to"))
        key = (core._norm(name), round(current, 2), valid_from or "", valid_to or "")
        if key in seen:
            continue
        seen.add(key)
        original = core._float_price(deal.get("original_price_value") or deal.get("original_price"))
        if original is not None and original <= current:
            original = None
        discount = deal.get("discount_percent")
        if discount is None:
            discount = core._discount_percent(current, original, deal.get("discount_text") or "")
        cleaned.append({
            **deal,
            "name": name[:180],
            "price_value": current,
            "price_text": core._fmt_price(current),
            "original_price_value": original,
            "original_price": core._fmt_price(original) if original else "",
            "discount_percent": discount,
            "valid_from": valid_from,
            "valid_to": valid_to,
        })

    if not cleaned:
        return 0

    marker = SOURCE_PREFIX + store + ":" + fingerprint
    now = _now_iso()
    with core.db() as conn:
        conn.execute("DELETE FROM official_deals WHERE store=? AND source_kind='official'", (store,))
        for deal in cleaned[:1800]:
            group_key, group_label = core._group_for(deal["name"])
            conn.execute(
                """
                INSERT INTO official_deals(
                    store, name, name_norm, group_key, group_label,
                    price_text, price_value, original_price, original_price_value,
                    discount_percent, amount, valid_from, valid_to,
                    source_url, source_kind, source_fingerprint, updated_at
                ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """,
                (
                    store,
                    deal["name"],
                    core._norm(deal["name"]),
                    group_key,
                    group_label,
                    deal["price_text"],
                    deal["price_value"],
                    deal.get("original_price") or "",
                    deal.get("original_price_value"),
                    deal.get("discount_percent"),
                    core._clean(deal.get("amount"))[:100],
                    deal.get("valid_from"),
                    deal.get("valid_to"),
                    core._clean(deal.get("source_url"))[:1000],
                    "official",
                    marker,
                    now,
                ),
            )
        conn.commit()
    return len(cleaned)


# ---------------------------------------------------------------------------
# Lidl: consume an existing Home Assistant integration instead of scraping Lidl.
# Recommended integration: https://github.com/FaserF/ha-lidl
# Its Offers / Offers Preview sensors expose fully structured `discounts` arrays.
# ---------------------------------------------------------------------------


def _ha_states():
    token = os.environ.get("SUPERVISOR_TOKEN", "").strip()
    if not token:
        raise RuntimeError("SUPERVISOR_TOKEN není dostupný")
    response = requests.get(
        HA_STATES_URL,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        timeout=15,
    )
    response.raise_for_status()
    data = response.json()
    if not isinstance(data, list):
        raise RuntimeError("Home Assistant /states nevrátil seznam")
    return data


def _lidl_sensor_states(states):
    matches = []
    for state in states:
        if not isinstance(state, dict):
            continue
        entity_id = str(state.get("entity_id") or "")
        attrs = state.get("attributes") or {}
        if not entity_id.startswith("sensor.") or not isinstance(attrs, dict):
            continue
        discounts = attrs.get("discounts")
        if not isinstance(discounts, list):
            continue
        # ha-lidl exposes these store fields on both Offers and Offers Preview.
        if str(attrs.get("store_country") or "").upper() != "CZ":
            continue
        if not attrs.get("store_key"):
            continue
        matches.append(state)
    return matches


def _sync_lidl_from_ha():
    states = _ha_states()
    sensors = _lidl_sensor_states(states)
    if not sensors:
        raise RuntimeError(
            "nenašel jsem senzory Lidl Weekly Offers v Home Assistantu; nainstaluj a nastav integraci FaserF/ha-lidl pro CZ"
        )

    deals = []
    fingerprint_rows = []
    sensor_names = []
    for state in sensors:
        attrs = state.get("attributes") or {}
        sensor_names.append(state.get("entity_id") or "")
        discounts = attrs.get("discounts") or []
        for offer in discounts:
            if not isinstance(offer, dict):
                continue
            name = core._clean(offer.get("title") or offer.get("name") or "")
            current = core._float_price(offer.get("price"))
            if not name or current is None:
                continue
            old = core._float_price(offer.get("old_price"))
            discount_text = core._clean(offer.get("discount"))
            deals.append({
                "name": name,
                "price_value": current,
                "original_price_value": old,
                "discount_percent": core._discount_percent(current, old, discount_text),
                "discount_text": discount_text,
                "amount": core._clean(offer.get("packaging") or offer.get("price_per_unit") or ""),
                "valid_from": offer.get("start_date"),
                "valid_to": offer.get("end_date"),
                "source_url": "",
            })
            fingerprint_rows.append({
                "id": offer.get("id"),
                "title": name,
                "price": offer.get("price"),
                "old_price": offer.get("old_price"),
                "start": offer.get("start_date"),
                "end": offer.get("end_date"),
            })

    if not deals:
        raise RuntimeError("Lidl integrace je nalezená, ale její Offers senzory zatím neobsahují žádné nabídky")

    fingerprint = hashlib.sha256(
        json.dumps(fingerprint_rows, ensure_ascii=False, sort_keys=True, default=str).encode("utf-8")
    ).hexdigest()
    count = _replace_store("lidl", deals, fingerprint)
    _log(f"Lidl přes Home Assistant: {count} nabídek ze {len(sensors)} senzorů ({', '.join(sensor_names)})")
    return count


# ---------------------------------------------------------------------------
# Albert: optional managed Parse.bot API. We deliberately consume only structured
# product objects. OCR text is NOT parsed by Haneva anymore.
# ---------------------------------------------------------------------------


def _parse_get(endpoint, api_key, params=None):
    response = requests.get(
        f"{PARSE_BASE}/{endpoint}",
        headers={"X-API-Key": api_key, "Accept": "application/json"},
        params=params or {},
        timeout=35,
    )
    response.raise_for_status()
    return response.json()


def _leaflets_from_response(payload):
    out = []
    seen = set()
    for obj in _walk(payload):
        view = obj.get("viewUrl") or obj.get("view_url")
        if not view:
            continue
        view = str(view)
        slug = urlparse(view).path.rstrip("/").split("/")[-1]
        if not slug or slug in seen:
            continue
        seen.add(slug)
        out.append({
            "slug": slug,
            "view_url": view,
            "valid_from": obj.get("validityStartDateFormatted") or obj.get("validityStartDate") or obj.get("valid_from"),
            "valid_to": obj.get("validityEndDateFormatted") or obj.get("validityEndDate") or obj.get("valid_to"),
        })
    return out


def _structured_products(payload, leaflet):
    """Accept product JSON only; never interpret Parse OCR/free text ourselves."""
    products = []
    name_keys = ("productName", "product_name", "name", "title")
    price_keys = ("promoPrice", "salePrice", "currentPrice", "current_price", "price")
    old_keys = ("oldPrice", "originalPrice", "regularPrice", "previousPrice", "old_price")
    amount_keys = ("amount", "packaging", "unit", "size")
    for obj in _walk(payload):
        if not isinstance(obj, dict):
            continue
        # OCR spread/page objects contain text and imageUrl but no explicit product price field.
        name = next((obj.get(k) for k in name_keys if obj.get(k) not in (None, "")), None)
        price_raw = next((obj.get(k) for k in price_keys if obj.get(k) not in (None, "")), None)
        if name is None or price_raw is None:
            continue
        current = core._float_price(price_raw)
        name = core._clean(name)
        if current is None or not name or len(name) < 2:
            continue
        old_raw = next((obj.get(k) for k in old_keys if obj.get(k) not in (None, "")), None)
        old = core._float_price(old_raw)
        products.append({
            "name": name,
            "price_value": current,
            "original_price_value": old,
            "discount_percent": core._discount_percent(current, old, obj.get("discount") or obj.get("discountPercent") or ""),
            "amount": core._clean(next((obj.get(k) for k in amount_keys if obj.get(k)), "")),
            "valid_from": obj.get("valid_from") or obj.get("validFrom") or leaflet.get("valid_from"),
            "valid_to": obj.get("valid_to") or obj.get("validTo") or leaflet.get("valid_to"),
            "source_url": leaflet.get("view_url") or "",
        })
    return products


def _sync_albert_parse():
    api_key = str(_options().get("parse_api_key") or "").strip()
    if not api_key:
        _log("Albert: Parse.bot není nastavený; starý PDF parser ani Kupi už nepoužívám")
        return 0

    current = _parse_get("get_current_leaflets", api_key)
    leaflets = _leaflets_from_response(current)
    if not leaflets:
        raise RuntimeError("Parse.bot nevrátil žádný aktuální Albert leták")

    # Do not burn credits repeatedly on the same published leaflet set.
    slugs = sorted(item["slug"] for item in leaflets[:4])
    slug_fingerprint = hashlib.sha256("|".join(slugs).encode()).hexdigest()
    if _meta_get("parse_albert_leaflets") == slug_fingerprint:
        existing = _count_external("albert")
        _log(f"Albert přes Parse.bot: letáky se nezměnily, ponechávám {existing} uložených nabídek")
        return existing

    deals = []
    for leaflet in leaflets[:4]:
        detail = _parse_get("get_leaflet_detail", api_key, {"id": leaflet["slug"]})
        deals.extend(_structured_products(detail, leaflet))

    _meta_set("parse_albert_leaflets", slug_fingerprint)
    if not deals:
        _log(
            "Albert přes Parse.bot: API funguje, ale veřejný get_leaflet_detail vrací jen OCR stránky, ne strukturované produkty; "
            "Haneva OCR záměrně neparsuje. Je potřeba v Parse.bot doplnit endpoint/fields pro products."
        )
        return 0

    fingerprint = hashlib.sha256(
        json.dumps(deals, ensure_ascii=False, sort_keys=True, default=str).encode("utf-8")
    ).hexdigest()
    count = _replace_store("albert", deals, fingerprint)
    _log(f"Albert přes Parse.bot: {count} strukturovaných nabídek")
    return count


def _sync_once():
    core.init_db()
    _clear_legacy_rows("lidl")
    _clear_legacy_rows("albert")

    counts = {"lidl": _count_external("lidl"), "albert": _count_external("albert")}
    errors = []

    try:
        counts["lidl"] = _sync_lidl_from_ha()
    except Exception as exc:
        message = f"Lidl HA integrace: {type(exc).__name__}: {exc}"
        errors.append(message)
        _log(message)

    try:
        counts["albert"] = _sync_albert_parse()
    except Exception as exc:
        message = f"Albert Parse.bot: {type(exc).__name__}: {exc}"
        errors.append(message)
        _log(message)

    _log(f"hotovo: Lidl={counts['lidl']}, Albert={counts['albert']}, errors={len(errors)}")
    return counts, errors


# Retire Kupi completely for the Akce page. If an external source is unavailable,
# the tab stays empty instead of silently showing a different data source.
core._fallback_rows = lambda store, query: []
core._sync_once = _sync_once

start_worker = core.start_worker
request_sync = core.request_sync
